import type { DoctorSummary } from "@kavach/types";

export interface PdfGenerationResult {
  buffer: Buffer;
  s3Key: string;
  s3Url: string;
}

/**
 * Generates the one-page doctor summary PDF.
 * Uses Puppeteer to render an HTML template to PDF.
 *
 * Design requirements (from docs/doctor-summary.md):
 * - A4 portrait, single page
 * - Patient snapshot header, 2-column body, portal QR bottom-right
 * - Readable at 6-inch phone screen without zoom
 * - Doctor should be able to scan in under 60 seconds
 */
export async function generateDoctorSummaryPdf(
  summary: DoctorSummary,
  patientId: string
): Promise<PdfGenerationResult> {
  // TODO: Implement with Puppeteer
  // 1. Load HTML template from templates/doctor-summary.html
  // 2. Inject summary data (Handlebars or similar)
  // 3. Launch Puppeteer, set page content, print to PDF
  // 4. Upload PDF buffer to S3
  // 5. Return S3 key and URL
  throw new Error("generateDoctorSummaryPdf not yet implemented");
}

export function buildSummaryHtml(summary: DoctorSummary): string {
  // TODO: Build HTML string for the doctor summary
  // Sections: patient snapshot, conditions, medications, lab trends, visits, upcoming, portal QR
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8" />
  <title>Kavach — Medical Summary</title>
  <style>
    /* Doctor summary styles — see docs/doctor-summary.md for design requirements */
    body { font-family: Inter, sans-serif; font-size: 11pt; margin: 0; padding: 16px; }
    .header { background: #1a1a2e; color: white; padding: 12px; border-radius: 4px; margin-bottom: 12px; }
    .patient-name { font-size: 18pt; font-weight: bold; }
    .section-title { font-weight: bold; color: #1a1a2e; border-bottom: 1px solid #ccc; margin-top: 8px; }
    .provisional { color: #888; font-size: 8pt; font-style: italic; }
  </style>
</head>
<body>
  <div class="header">
    <div class="patient-name">${summary.patientSnapshot.name}</div>
    <div>Age: ${summary.patientSnapshot.age ?? "—"} | Blood Group: ${summary.patientSnapshot.bloodGroup ?? "—"} | Weight: ${summary.patientSnapshot.weightKg ? summary.patientSnapshot.weightKg + " kg" : "—"}</div>
  </div>
  <!-- TODO: Render all 7 sections with proper layout -->
  <div class="provisional">Generated by Kavach · ${new Date(summary.generatedAt).toLocaleDateString("en-IN")} · Valid for 8 hours</div>
</body>
</html>
  `.trim();
}
